const screens=[...document.querySelectorAll('.screen')],bar=document.getElementById('progressBar');
const order=['cover','story1','question1','experiment1','story2','question2','experiment2','water','question3','vacuum','space','memory','ending','teaser'];
let audioOn=true,ctx=null;
function tone(freq=220,dur=.18,type='sine',vol=.035){if(!audioOn)return;try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+dur);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+dur)}catch(e){}}
function bell(){tone(120,.8,'sine',.07);setTimeout(()=>tone(240,.45,'sine',.025),35)}
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));const i=order.indexOf(id);bar.style.width=(Math.max(0,i)/(order.length-1)*100)+'%';window.scrollTo(0,0);if(id==='story1')setTimeout(bell,500);if(id==='space')setTimeout(()=>tone(520,.7,'sine',.018),500)}
document.addEventListener('click',e=>{const b=e.target.closest('[data-next]');if(b){tone(330,.08,'sine',.018);show(b.dataset.next)}});
const answers={q1:{right:'paths',next:'experiment1',ok:'对。不是两个钟声，而是同一次振动沿不同介质传播。去实验室看看哪条路更快。',bad:'这个解释很诱人，但它解释不了为什么贴着墙反而先听到。试着把“一个声音”想成“同一次振动的两条路线”。'},q2:{right:'vibration',next:'experiment2',ok:'成立。钟先振动，再让周围介质发生一连串振动。声音不是独立飞行的小东西。',bad:'再想一步：如果声音是独立飞出来的东西，为什么换一种介质，它的传播速度会明显改变？'},q3:{right:'no',next:'vacuum',ok:'成立。没有介质，就没有下一层粒子接过振动。我们用一个玻璃罩把空气慢慢拿走。',bad:'关键不是声音够不够大，而是有没有物质继续这场“接力”。'},q4:{right:'see',next:'memory',ok:'成立。太阳的光能穿过真空抵达我们；声波却不能靠真空把机械振动传来。',bad:'爆发再猛烈，也不能让机械声波跨越近乎真空的太空。光和声音遵守的是不同的传播规则。'}};
document.querySelectorAll('.choices').forEach(group=>group.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;const q=group.dataset.question,cfg=answers[q];[...group.children].forEach(x=>x.disabled=true);const good=btn.dataset.value===cfg.right;btn.classList.add(good?'correct':'wrong');if(!good)[...group.children].find(x=>x.dataset.value===cfg.right)?.classList.add('correct');tone(good?520:180,good?.18:.28,good?'sine':'triangle',.03);const fb=document.getElementById(q+'-feedback');fb.innerHTML=(good?'<strong>成立。</strong> ':'<strong>再看一步。</strong> ')+(good?cfg.ok:cfg.bad)+`<br><button class="primary" style="margin-top:14px" data-next="${cfg.next}">继续</button>`}));
const tapBtn=document.getElementById('tapBtn');tapBtn.addEventListener('click',()=>{bell();const solid=document.querySelector('.pulse.solid'),air=document.querySelector('.pulse.air');solid.classList.remove('go');air.classList.remove('go');void solid.offsetWidth;solid.classList.add('go');air.classList.add('go');document.getElementById('solidTime').textContent='先到 · 约 3500 m/s';document.getElementById('airTime').textContent='后到 · 约 343 m/s';setTimeout(()=>document.getElementById('exp1next').classList.remove('hidden'),850)});
const slider=document.getElementById('distance');function updateTimes(){const d=+slider.value,meters=d*2,ts=meters/3500,ta=meters/343;document.getElementById('tSolid').textContent=ts.toFixed(3)+' s';document.getElementById('tAir').textContent=ta.toFixed(3)+' s';document.getElementById('tGap').textContent=(ta-ts).toFixed(3)+' s';document.getElementById('observer').style.right=(100-d)*.22+'%'}slider.addEventListener('input',updateTimes);updateTimes();
const vac=document.getElementById('vacuumSlider'),dots=document.getElementById('airDots'),pct=document.getElementById('airPct'),vtext=document.getElementById('vacuumText');function updateVac(){const v=+vac.value;pct.textContent=v+'%';dots.style.opacity=.08+.92*v/100;dots.style.transform=`scale(${.72+.28*v/100})`;if(v>65)vtext.textContent='铃在振动，空气也在把振动传向外面。';else if(v>25)vtext.textContent='空气变少了。能参与接力的粒子越来越少，铃声也越来越弱。';else vtext.textContent='接近真空：铃仍然可以振动，但几乎没有介质把声音传到外面。';if(v%10<3)tone(260,.08,'sine',.008*v/100)}vac.addEventListener('input',updateVac);updateVac();
document.getElementById('soundToggle').addEventListener('click',e=>{audioOn=!audioOn;e.currentTarget.textContent=audioOn?'♪ 声音':'× 静音';if(audioOn)tone(440,.12)});show('cover');