const $=(s,r=document)=>r.querySelector(s);
const REPO='taomuzhaotao/chapter11',API=`https://api.github.com/repos/${REPO}/issues?state=open&per_page=100&sort=created&direction=desc`,RECORD_MARK='mist-ch11-memory-v1';
const state=JSON.parse(localStorage.getItem('mist-memory-ch11-v1')||'{"page":0,"answers":{},"clues":[],"name":""}');
let audioOn=true,ambientOn=false,audioCtx=null,ambientTimer=null;
const svg={
 cinema:`<svg viewBox="0 0 640 480" aria-label="1974年的心理学实验室与事故影片"><defs><linearGradient id="c1" y2="1"><stop stop-color="#cbd3cb"/><stop offset="1" stop-color="#6c7c75"/></linearGradient></defs><rect width="640" height="480" fill="url(#c1)"/><rect x="65" y="55" width="510" height="292" fill="#eee9dc" stroke="#365148" stroke-width="10"/><rect x="90" y="82" width="460" height="235" fill="#778983"/><path d="M90 255l120-60 105 32 100-70 135 65v95H90z" fill="#4c5f58"/><path d="M198 200h95l42 38v39H165v-38z" fill="#243b35"/><circle cx="208" cy="279" r="24" fill="#192824"/><circle cx="292" cy="279" r="24" fill="#192824"/><path d="M352 210h90l48 38v35H328v-36z" fill="#a37242"/><circle cx="365" cy="284" r="23" fill="#272a27"/><circle cx="452" cy="284" r="23" fill="#272a27"/><path d="M330 195l22 21-27 17 19 23-38-8-12 34-15-37-38 5 25-26-22-25 38 4 14-34 13 35z" fill="#e2b657"/><g fill="#273d37"><circle cx="140" cy="395" r="38"/><path d="M90 480v-34q0-52 100-52t100 52v34z"/><circle cx="495" cy="405" r="34"/><path d="M450 480v-28q0-47 90-47t90 47v28z"/></g></svg>`,
 form:`<svg viewBox="0 0 640 480" aria-label="五份只差一个动词的问卷"><rect width="640" height="480" fill="#dfe5dd"/><g transform="translate(70 48) rotate(-4 245 190)"><rect width="500" height="380" fill="#faf7ed" stroke="#aeb9af" stroke-width="4"/><text x="42" y="62" fill="#31554a" font-size="19">关于影片中的交通事故</text><path d="M42 82h416" stroke="#bac3ba"/><text x="42" y="132" fill="#566b63" font-size="17">两辆车彼此 ______ 时，大约有多快？</text><g font-size="18" fill="#785c35"><text x="55" y="205">contacted · 接触</text><text x="55" y="246">hit · 撞上</text><text x="55" y="287">bumped · 碰撞</text><text x="305" y="205">collided · 相撞</text><text x="305" y="246">smashed · 猛撞</text></g><g fill="none" stroke="#6c8379" stroke-width="3"><circle cx="42" cy="198" r="8"/><circle cx="42" cy="239" r="8"/><circle cx="42" cy="280" r="8"/><circle cx="292" cy="198" r="8"/><circle cx="292" cy="239" r="8"/></g><path d="M42 332h410M42 350h350" stroke="#c9cec7" stroke-width="3"/></g></svg>`,
 graph:`<svg viewBox="0 0 640 480" aria-label="不同动词组的平均速度估计"><rect width="640" height="480" fill="#edf0e8"/><path d="M90 60v340h490" stroke="#526a61" stroke-width="4"/><g fill="#9b7440"><rect x="120" y="145" width="62" height="255"/><rect x="215" y="177" width="62" height="223"/><rect x="310" y="194" width="62" height="206"/><rect x="405" y="226" width="62" height="174"/><rect x="500" y="252" width="62" height="148"/></g><g fill="#38594e" font-size="18" text-anchor="middle"><text x="151" y="130">40.8</text><text x="246" y="162">39.3</text><text x="341" y="179">38.1</text><text x="436" y="211">34.0</text><text x="531" y="237">31.8</text></g><g fill="#60736b" font-size="14" text-anchor="middle"><text x="151" y="428">猛撞</text><text x="246" y="428">相撞</text><text x="341" y="428">碰撞</text><text x="436" y="428">撞上</text><text x="531" y="428">接触</text></g></svg>`,
 week:`<svg viewBox="0 0 640 480" aria-label="一周后的第二次问卷"><rect width="640" height="480" fill="#cbd6d0"/><circle cx="118" cy="105" r="65" fill="#f1e5c5"/><path d="M118 105V62M118 105l34 21" stroke="#52665e" stroke-width="7" stroke-linecap="round"/><path d="M75 185q43 32 86 0" fill="none" stroke="#7d9188" stroke-width="5"/><g transform="translate(215 55) rotate(3 170 180)"><rect width="350" height="370" fill="#faf7ed" stroke="#aeb9af" stroke-width="4"/><text x="34" y="58" fill="#31554a" font-size="18">关于上周的影片</text><path d="M34 78h282" stroke="#bdc5bd"/><text x="34" y="130" fill="#4c6259" font-size="18">你看见碎玻璃了吗？</text><rect x="38" y="165" width="120" height="52" fill="#e7ece5"/><text x="98" y="198" text-anchor="middle" fill="#345a4e" font-size="20">看见了</text><rect x="190" y="165" width="120" height="52" fill="#e7ece5"/><text x="250" y="198" text-anchor="middle" fill="#345a4e" font-size="20">没有</text><path d="M35 266h280M35 290h250M35 314h275" stroke="#c8cec7" stroke-width="4"/></g></svg>`,
 glass:`<svg viewBox="0 0 640 480" aria-label="影片中不存在的碎玻璃"><rect width="640" height="480" fill="#465852"/><path d="M0 330l150-80 150 42 120-100 220 92v196H0z" fill="#6f7c75"/><path d="M170 245h120l60 50v55H130v-56z" fill="#233b35"/><circle cx="180" cy="350" r="32" fill="#192722"/><circle cx="300" cy="350" r="32" fill="#192722"/><path d="M370 250h115l65 52v55H330v-58z" fill="#a37443"/><circle cx="390" cy="358" r="31" fill="#252b27"/><circle cx="510" cy="358" r="31" fill="#252b27"/><path d="M332 228l28 28-35 23 25 30-49-10-15 44-19-48-50 7 33-35-29-32 50 6 18-45 17 46z" fill="#e4b75a"/><text x="320" y="438" text-anchor="middle" fill="#eef1e9" font-size="21">注意：原影片中没有碎玻璃</text></svg>`,
 memory:`<svg viewBox="0 0 640 480" aria-label="事件、后来信息与提问共同进入记忆"><rect width="640" height="480" fill="#e8ece5"/><g transform="translate(45 75)"><circle cx="85" cy="85" r="78" fill="#5e7b70"/><text x="85" y="78" text-anchor="middle" fill="white" font-size="19">原始事件</text><text x="85" y="108" text-anchor="middle" fill="#dbe8e1" font-size="14">事故影片</text><circle cx="275" cy="85" r="78" fill="#a8834d"/><text x="275" y="78" text-anchor="middle" fill="white" font-size="19">事后信息</text><text x="275" y="108" text-anchor="middle" fill="#f4e6ce" font-size="14">“猛撞”</text><circle cx="465" cy="85" r="78" fill="#71808a"/><text x="465" y="78" text-anchor="middle" fill="white" font-size="19">检索问题</text><text x="465" y="108" text-anchor="middle" fill="#e3e8eb" font-size="14">“碎玻璃？”</text><path d="M130 145L230 270M275 163v107M420 145L320 270" stroke="#84978e" stroke-width="8"/><path d="M210 270h130l45 68-110 55-110-55z" fill="#304f45"/><text x="275" y="326" text-anchor="middle" fill="white" font-size="21">后来报告的记忆</text><text x="275" y="355" text-anchor="middle" fill="#cddbd4" font-size="14">来源可能被混淆</text></g></svg>`,
 interview:`<svg viewBox="0 0 640 480" aria-label="开放式与诱导式访谈的对比"><rect width="640" height="480" fill="#dce4dc"/><path d="M320 35v410" stroke="#bdc7be" stroke-width="4"/><g><circle cx="105" cy="175" r="42" fill="#c9936b"/><path d="M62 390V260q0-50 86-50t86 50v130" fill="#38594f"/><circle cx="235" cy="190" r="37" fill="#b98264"/><path d="M198 390V270q0-45 74-45t48 45v120" fill="#6d7d76"/><rect x="35" y="55" width="240" height="78" rx="30" fill="#faf8ef"/><text x="155" y="87" text-anchor="middle" fill="#31564b" font-size="16">请从头说说</text><text x="155" y="111" text-anchor="middle" fill="#31564b" font-size="16">你记得什么。</text></g><g transform="translate(320)"><circle cx="105" cy="175" r="42" fill="#c9936b"/><path d="M62 390V260q0-50 86-50t86 50v130" fill="#38594f"/><circle cx="235" cy="190" r="37" fill="#b98264"/><path d="M198 390V270q0-45 74-45t48 45v120" fill="#6d7d76"/><rect x="35" y="55" width="255" height="78" rx="30" fill="#f2dfd3"/><text x="162" y="87" text-anchor="middle" fill="#804f42" font-size="16">车猛撞以后，</text><text x="162" y="111" text-anchor="middle" fill="#804f42" font-size="16">玻璃飞向哪里？</text></g></svg>`
};
const pages=[
 {title:'放映结束以后',skill:'分开事件与报告',kind:'story',visual:'cinema',caption:'美国华盛顿大学 · 1974 年',chapter:'第 1 页 · 一个不稳定的证人',text:'学生们看完几段真实交通事故影片。画面已经结束，但实验真正关心的不是事故本身，而是人们稍后怎样报告它。伊丽莎白·洛夫特斯与约翰·帕默想追问：提问只是读取记忆，还是也会改变记忆？',evidence:['已知','所有人看到同类事故影片','随后','研究者改变问题中的一个动词','目标','把事件本身与事后语言分开'],source:'Loftus 与 Palmer 于 1974 年发表两项实验，研究事后提问措辞如何影响速度估计与后来对碎玻璃的报告。'},
 {title:'怎样才能抓住一句话的作用？',skill:'设计随机对照',kind:'question',visual:'form',prompt:'如果想判断“提问中的动词”是否造成差异，最关键的设计是什么？',options:[['ask','让同一名学生依次回答五种问法'],['random','让参与者随机进入不同动词组，其他流程保持相同'],['expert','只询问熟悉驾驶的人']],correct:'random',feedback:'随机分组让各组在平均意义上更可比较；只改变动词，才更有理由把组间差异归因于问题措辞。',clue:['随机对照','把参与者随机分组，只改变问题中的动词。'],source:'随机分配与保持其他流程一致，是从“相关差异”迈向因果解释的关键。'},
 {title:'只换一个动词',skill:'操纵自变量',kind:'wordlab',source:'实验一使用五个动词：smashed、collided、bumped、hit、contacted。平均速度估计依次约为 40.8、39.3、38.1、34.0、31.8 mph。'},
 {title:'同一段影片，五种速度',skill:'读取组间模式',kind:'story',visual:'graph',caption:'实验一 · 平均速度估计（mph）',chapter:'第 4 页 · 数据出现斜坡',text:'“猛撞”组给出的平均速度约为 40.8 mph，“接触”组约为 31.8 mph。影片没有改变，变化的是事后问题。动词越强烈，平均估计越高。',evidence:['猛撞 smashed','40.8 mph','接触 contacted','31.8 mph','组间差','约 9 mph'],source:'论文报告动词条件对速度估计产生显著影响。数值是组平均，不代表每个人都会被同样影响。'},
 {title:'速度变了，记忆就一定变了吗？',skill:'比较竞争解释',kind:'question',visual:'graph',prompt:'仅凭实验一，哪项结论最严谨？',options:[['memory','动词已经永久改写了所有人的视觉记忆'],['bias','措辞影响了回答；可能是反应偏差，也可能是记忆表征变化'],['lie','学生知道答案却故意撒谎']],correct:'bias',feedback:'速度估计差异本身无法区分“为了配合问题而报得更高”和“事后信息进入了记忆”。需要第二个实验制造更强的检验。',clue:['竞争解释','同一结果可能来自回答偏差，也可能来自记忆变化。'],source:'好实验不仅问“有没有效应”，还要设计后续证据来区分产生效应的不同机制。'},
 {title:'一周以后，再问一次',skill:'延迟检验',kind:'story',visual:'week',caption:'实验二 · 延迟一周',chapter:'第 6 页 · 一个不存在的细节',text:'新的 150 名参与者被分为“猛撞”“撞上”和不问速度的控制组。整整一周后，研究者问：“你看见碎玻璃了吗？”关键在于——影片里根本没有碎玻璃。',evidence:['三组','猛撞 / 撞上 / 控制','等待','一周','关键事实','影片中没有碎玻璃'],source:'实验二每组 50 人。一周后所有人回答关于碎玻璃的问题；这是对虚假细节报告的检验。'},
 {title:'把不存在的玻璃写进表格',skill:'检验关键预测',kind:'glasslab',source:'回答“看见碎玻璃”的人数：猛撞组 16/50，撞上组 7/50，控制组 6/50。多数人仍回答正确，但组间差异支持事后措辞的影响。'},
 {title:'16、7、6意味着什么？',skill:'避免过度概括',kind:'question',visual:'glass',prompt:'面对三组结果，哪种解释最符合证据？',options:[['all','强烈动词会让每个人都形成虚假记忆'],['none','多数人没受影响，所以措辞完全没有作用'],['risk','强烈动词提高了报告不存在细节的概率，但并非决定每个人的记忆']],correct:'risk',feedback:'32% 不是 100%，但也明显高于 14% 和 12%。科学结论应描述概率变化，而不是把群体效应说成人人必然如此。',clue:['概率而非命运','诱导性措辞提高错误报告的风险，但不会决定每个人。'],source:'猛撞组 32%、撞上组 14%、控制组 12% 报告看见碎玻璃。结论针对组间概率，不是个体诊断。'},
 {title:'记忆不是录像回放',skill:'建立重构模型',kind:'story',visual:'memory',caption:'事件之后，信息仍在进入系统',chapter:'第 9 页 · 来源监控',text:'回忆更像一次重建：原始事件、后来听到的词、问题暗含的预设，都可能在检索时被拼在一起。人也许记得“碎玻璃”这个表象，却误把它的来源归给事故影片。',evidence:['来源一','真正看见的事件','来源二','后来听到的语言','错误','记得内容，却混淆它来自哪里'],source:'“来源监控”指判断信息来自知觉、想象、推断还是他人叙述。来源误归因是解释错误记忆的重要框架之一。'},
 {title:'拆开一段回忆的来源',skill:'来源监控',kind:'sourcelab',source:'区分内容与来源，可以降低把想象、暗示或后来信息误认为亲历事件的风险，但不能保证记忆完全准确。'},
 {title:'我非常确信，所以我一定正确？',skill:'校准置信度',kind:'question',visual:'memory',prompt:'一个目击者非常生动、非常确信地描述碎玻璃。最合理的判断是：',options:[['proof','高度确信本身足以证明细节真实'],['ignore','所有目击记忆都不可信，应全部忽略'],['separate','确信度与准确性必须分开评估，还要检查提问和事后信息']],correct:'separate',feedback:'生动感与确信感是真实的心理体验，却不自动构成外部事实的证明。可靠判断需要独立证据与无诱导的访谈过程。',clue:['确信不等于准确','主观确定感不能代替来源与独立证据。'],source:'记忆信心与准确性的关系受获取方式、反馈和访谈条件影响，不能把确信直接当作事实校验。'},
 {title:'实验室之外，问题会改变命运',skill:'迁移到真实情境',kind:'story',visual:'interview',caption:'两种问法，两种风险',chapter:'第 12 页 · 从实验到证词',text:'“请从头说说你记得什么”允许证人自行提取；“车猛撞后，玻璃飞向哪里”同时塞入了强烈动词和并不存在的前提。司法访谈、新闻采访和日常争执里，问题从来不只是容器。',evidence:['开放式','减少问题者提供的新信息','诱导式','把假设藏进问题','原则','先自由回忆，再澄清细节'],source:'现实证词还受压力、注意、时间间隔、重复提问与反馈等因素影响。本章实验只隔离了其中一部分。'},
 {title:'哪一种问法更安全？',skill:'应用证据',kind:'question',visual:'interview',prompt:'事故调查中，哪一个开场问题最不容易把新信息塞进证人的记忆？',options:[['where','“那辆超速的红车从哪里冲出来？”'],['tell','“请从你最早记得的时刻开始，按自己的顺序说发生了什么。”'],['glass','“碎玻璃落在车内还是路面？”']],correct:'tell',feedback:'开放式邀请不预设车辆颜色、速度或碎玻璃。后续仍可澄清，但应记录问题本身，因为提问也可能成为事后信息。',clue:['开放式提问','让证人先自由报告，避免把未经证实的细节写进问题。'],source:'开放式提问不能消除全部错误，但能减少访谈者通过措辞引入特定内容的机会。'},
 {title:'你的证据链',skill:'整合机制与限制',kind:'map',source:'本章据 Loftus & Palmer (1974) 两项实验整理。经典结果重要，但解释任何现实个案仍需结合更多证据。'},
 {title:'调查归档',skill:'查看成绩',kind:'result',source:'你的得分结合首次判断与尝试次数。错误不会阻止继续，它们用于呈现推理怎样被证据修正。'}
];
function save(){localStorage.setItem('mist-memory-ch11-v1',JSON.stringify(state))}
function tone(f=330,d=.12,v=.025){if(!audioOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(v,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(e){}}
function projector(){tone(72,.35,.018);setTimeout(()=>tone(92,.25,.012),180)}
function setAmbient(on){ambientOn=on;$('#ambientBtn').textContent=`氛围声${on?'开':'关'}`;clearInterval(ambientTimer);if(on){projector();ambientTimer=setInterval(()=>tone(66+Math.random()*18,.5,.005),2400)}}
function storyHTML(p){return `<div class="story-grid"><figure class="visual"><figcaption>${p.caption}</figcaption>${svg[p.visual]}<button class="inspect" data-action="inspect">查看图像 ↗</button></figure><section class="copy"><p class="chapter">${p.chapter}</p><h1>${p.title}</h1><p>${p.text}</p><div class="clue-card">${p.evidence.map((x,i)=>i%2===0?`<div><small>${x}</small><b>${p.evidence[i+1]}</b></div>`:'').join('')}</div></section></div>`}
function questionHTML(p,i){const previous=state.answers[i];return `<section class="question-page"><header><p>推理节点 · 只依据目前证据判断</p><h1>${p.title}</h1><p>${p.prompt}</p></header><div class="question-stage"><div class="mini-visual">${svg[p.visual]}</div><div><div class="answers">${p.options.map(o=>`<button class="answer ${previous?(o[0]===p.correct?'correct':(o[0]===previous.choice?'wrong':'')):''}" data-answer="${o[0]}" ${previous?'disabled':''}>${o[1]}</button>`).join('')}</div><div class="feedback ${previous?'':'hidden'}">${previous?`<b>${previous.correct?'证据吻合。':'这一步需要修正。'}</b><br>${p.feedback}`:''}</div></div></div></section>`}
function wordLabHTML(){return `<section class="lab"><p class="kicker">实验一 · 语言操纵</p><h1>只换一个词，估计会移动吗？</h1><p>五组看到同类影片，却收到不同动词。点击动词，比较该组的平均速度估计。</p><div class="word-lab"><div class="mini-visual">${svg.form}</div><div class="verb-panel"><div class="verb-buttons"><button data-verb="猛撞" data-speed="40.8">猛撞</button><button data-verb="相撞" data-speed="39.3">相撞</button><button data-verb="碰撞" data-speed="38.1">碰撞</button><button data-verb="撞上" data-speed="34.0">撞上</button><button data-verb="接触" data-speed="31.8">接触</button></div><div class="speed-read"><span id="verbName">选择一个动词</span><strong id="speedValue">—</strong><small>平均估计 · mph</small></div><div class="speed-track"><i id="speedBar"></i></div><p id="verbNote">影片相近，问题中的动词不同。</p></div></div></section>`}
function glassLabHTML(){return `<section class="lab"><p class="kicker">实验二 · 不存在的细节</p><h1>三组里，谁“看见”了碎玻璃？</h1><p>每组 50 人。先预测哪组错误报告最多，再翻开一周后的记录。</p><div class="prediction"><button data-predict="smashed">猛撞组</button><button data-predict="hit">撞上组</button><button data-predict="control">控制组</button></div><button id="revealGlass" class="run-test">翻开记录</button><div id="glassTable" class="glass-table hidden"><div><b>16 / 50</b><span>猛撞组 · 32%</span></div><div><b>7 / 50</b><span>撞上组 · 14%</span></div><div><b>6 / 50</b><span>控制组 · 12%</span></div><p>三组看到的影片都没有碎玻璃。</p></div></section>`}
function sourceLabHTML(){return `<section class="lab"><p class="kicker">机制台 · 来源监控</p><h1>这块“玻璃”究竟从哪里来？</h1><p>点击三类信息。它们会在回忆时同时变得可用，但来源并不相同。</p><div class="source-grid"><button data-source="event"><b>事故影片</b><span>两辆车发生碰撞</span></button><button data-source="after"><b>事后措辞</b><span>“猛撞”暗示严重程度</span></button><button data-source="question"><b>后来提问</b><span>“你看见碎玻璃了吗？”</span></button></div><div id="sourceResult" class="feedback"><b>尚未检查来源</b><br>记得某个内容，不等于记得它真正来自哪里。</div></section>`}
function mapHTML(){return `<section class="result-page"><p class="kicker">线索本 · 证据链闭合</p><h1>记忆是一种重建</h1><p>语言不是从外面简单地“敲门”。它可能成为后来重建事件时所用的材料。</p><div class="memory-chain"><div><b>① 编码</b><span>看见事故影片</span></div><i>→</i><div><b>② 事后信息</b><span>听见“猛撞”</span></div><i>→</i><div><b>③ 检索</b><span>被问到碎玻璃</span></div><i>→</i><div><b>④ 来源判断</b><span>把暗示误作亲眼所见</span></div></div><div class="evidence"><b>结论的边界</b>效应改变的是群体中的错误概率，不意味着每个人必然形成虚假记忆，也不能仅凭一次实验判断某个证人一定错误。</div></section>`}
function scoreData(){const qs=pages.map((p,i)=>p.kind==='question'?i:null).filter(i=>i!==null),correct=qs.filter(i=>state.answers[i]?.correct).length,attempts=qs.reduce((n,i)=>n+(state.answers[i]?.attempts||0),0),score=Math.round((correct/qs.length)*70+Math.max(0,30-(attempts-correct)*6));return{correct,attempts,score,total:qs.length}}
function escapeAttr(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function resultHTML(){const{correct,attempts,score,total}=scoreData();return `<section class="result-page"><p class="kicker">第十一章 · 调查完成</p><h1>${score>=90?'你守住了证据的来源':score>=70?'你识别了记忆的裂缝':'再检查一次竞争解释'}</h1><div class="score-ring" style="--score:${score*3.6}deg"><strong>${score}</strong></div><p>你从一个动词出发，追踪了速度估计、延迟测试与不存在的碎玻璃，也学会把确信、准确和信息来源分开。</p><div class="result-grid"><div><b>${correct}/${total}</b>独立答对</div><div><b>${state.clues.length}</b>条线索</div><div><b>${attempts}</b>次判断</div></div><section class="share-card"><h2>上传成绩与留言</h2><p>提交后，你的成绩和留言会公开出现在本章排行榜。GitHub 会在发布前让你确认内容。</p><div class="share-fields"><input id="playerName" maxlength="24" placeholder="排行榜显示名" value="${escapeAttr(state.name||'')}"><select id="playerRating" aria-label="给本章评分"><option value="5">★★★★★ · 5分</option><option value="4">★★★★☆ · 4分</option><option value="3">★★★☆☆ · 3分</option><option value="2">★★☆☆☆ · 2分</option><option value="1">★☆☆☆☆ · 1分</option></select><textarea id="playerComment" maxlength="500" placeholder="哪一步改变了你对记忆的看法？（可选）"></textarea></div><div class="share-submit"><button id="shareResult">去 GitHub 确认上传</button><small>需要登录 GitHub。确认发布后，返回本页刷新记录。</small></div><div id="submitNote" class="submit-note"></div></section><div class="result-actions"><button class="light" data-action="community">查看公共排行榜与留言</button><button class="light" data-action="notebook">回看线索本</button><button class="light" data-action="restart">重新调查</button></div></section>`}
function render(){state.page=Math.max(0,Math.min(pages.length-1,state.page));const p=pages[state.page];$('#skillLabel').textContent=p.skill;$('#pageNumber').textContent=`${String(state.page+1).padStart(2,'0')} / ${pages.length}`;$('#progressBar').style.width=`${(state.page+1)/pages.length*100}%`;$('#prevBtn').disabled=state.page===0;$('#nextBtn').disabled=p.kind==='question'&&!state.answers[state.page];$('#nextBtn').textContent=state.page===pages.length-1?'回到封面':'下一页';$('#page').innerHTML=p.kind==='story'?storyHTML(p):p.kind==='question'?questionHTML(p,state.page):p.kind==='wordlab'?wordLabHTML():p.kind==='glasslab'?glassLabHTML():p.kind==='sourcelab'?sourceLabHTML():p.kind==='map'?mapHTML():resultHTML();save();bindPage();updateTools();window.scrollTo({top:0,behavior:'smooth'});if(state.page===0)setTimeout(projector,400)}
function bindPage(){document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));document.querySelectorAll('[data-verb]').forEach(b=>b.onclick=()=>{const n=+b.dataset.speed;document.querySelectorAll('[data-verb]').forEach(x=>x.classList.toggle('selected',x===b));$('#verbName').textContent=b.dataset.verb;$('#speedValue').textContent=n.toFixed(1);$('#speedBar').style.width=`${(n-28)/15*100}%`;$('#verbNote').textContent=n>=40?'这个词暗示了一次更猛烈的事故。':n<33?'这个词暗示的接触更轻。':'估计落在两端之间。';tone(230+n*5,.12,.018)});document.querySelectorAll('[data-predict]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-predict]').forEach(x=>x.classList.toggle('selected',x===b));tone(300,.1,.015)});$('#revealGlass')?.addEventListener('click',()=>{$('#glassTable').classList.remove('hidden');$('#revealGlass').textContent='记录已打开';tone(520,.18,.02)});document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-source]').forEach(x=>x.classList.toggle('selected',x===b));const texts={event:'影片提供了“发生碰撞”，但没有碎玻璃。',after:'“猛撞”提供了严重事故的语义框架。',question:'碎玻璃问题让一个未出现的细节进入检索现场。'};$('#sourceResult').innerHTML=`<b>${b.querySelector('b').textContent}</b><br>${texts[b.dataset.source]}`;tone(360,.12,.016)});$('#shareResult')?.addEventListener('click',shareResult)}
function answer(choice){const p=pages[state.page],correct=choice===p.correct,old=state.answers[state.page];state.answers[state.page]={choice,correct,attempts:(old?.attempts||0)+1};if(p.clue&&!state.clues.includes(p.clue[0]))state.clues.push(p.clue[0]);tone(correct?520:170,correct?.18:.28,.025);render()}
function updateTools(){$('#clueCount').textContent=state.clues.length;$('#tocList').innerHTML=pages.map((p,i)=>`<li><button data-page="${i}" class="${i<=state.page?'done':''}"><span>${String(i+1).padStart(2,'0')} · ${p.title}</span></button></li>`).join('');$('#clueList').innerHTML=state.clues.length?state.clues.map(name=>{const p=pages.find(x=>x.clue?.[0]===name);return `<div class="clue"><b>${name}</b><p>${p?.clue?.[1]||''}</p></div>`}).join(''):'<p class="empty">线索还没有出现。继续阅读，在关键判断处收集它们。</p>'}
function openReader(page=0){$('#home').classList.add('hidden');$('#reader').classList.remove('hidden');state.page=page;render()}
function openHome(){$('#reader').classList.add('hidden');$('#home').classList.remove('hidden');$('.resume').classList.toggle('hidden',!localStorage.getItem('mist-memory-ch11-v1'));window.scrollTo(0,0)}
function shareResult(){const nickname=$('#playerName').value.trim(),comment=$('#playerComment').value.trim(),rating=+$('#playerRating').value,note=$('#submitNote');if(!nickname){note.textContent='请先填写排行榜显示名。';note.classList.add('show');$('#playerName').focus();return}if(nickname.length>24||comment.length>500){note.textContent='显示名最多 24 字，留言最多 500 字。';note.classList.add('show');return}state.name=nickname;save();const{correct,attempts,score,total}=scoreData(),record={app:'mist-adventure',version:1,kind:'score-comment',chapter:'memory-11',nickname,score,correct,total,attempts,rating,comment,submittedAt:new Date().toISOString()},body=`我完成了《记忆里的碎玻璃》。\n\n- 显示名：${nickname}\n- 成绩：${score} / 100\n- 独立答对：${correct} / ${total}\n- 评分：${'★'.repeat(rating)}${'☆'.repeat(5-rating)}\n${comment?`- 留言：${comment}\n`:''}\n> 这是一条由游戏生成的公开成绩记录。\n\n<!-- ${RECORD_MARK}\n${JSON.stringify(record)}\n-->`,title=`[第十一章成绩] ${nickname} · ${score}分`,url=`https://github.com/${REPO}/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`;note.textContent='已打开 GitHub。请点击“Submit new issue”完成公开上传。';note.classList.add('show');window.open(url,'_blank','noopener')}
function parseRecord(issue){if(issue.pull_request||typeof issue.body!=='string')return null;const m=issue.body.match(new RegExp(`<!--\\s*${RECORD_MARK}\\s*([\\s\\S]*?)\\s*-->`));if(!m)return null;try{const r=JSON.parse(m[1]);if(r.app!=='mist-adventure'||r.chapter!=='memory-11'||r.kind!=='score-comment')return null;if(typeof r.nickname!=='string'||r.nickname.length<1||r.nickname.length>24||!Number.isInteger(r.score)||r.score<0||r.score>100||!Number.isInteger(r.correct)||!Number.isInteger(r.total)||!Number.isInteger(r.attempts)||!Number.isInteger(r.rating)||r.rating<1||r.rating>5||typeof r.comment!=='string'||r.comment.length>500)return null;return{...r,issueUrl:issue.html_url,login:issue.user?.login||'player',createdAt:issue.created_at}}catch{return null}}
function addText(el,text){el.append(document.createTextNode(String(text)))}
async function loadCommunity(){const status=$('#communityStatus'),board=$('#communityBoard');status.classList.remove('hidden');status.textContent='正在读取大家的调查记录……';board.replaceChildren();try{const res=await fetch(API,{headers:{Accept:'application/vnd.github+json'}});if(!res.ok)throw new Error(`GitHub ${res.status}`);const issues=await res.json(),records=issues.map(parseRecord).filter(Boolean),best=new Map();records.forEach(r=>{const old=best.get(r.login);if(!old||r.score>old.score)best.set(r.login,r)});const ranking=[...best.values()].sort((a,b)=>b.score-a.score||b.correct-a.correct||a.attempts-b.attempts),comments=records.filter(r=>r.comment.trim()).slice(0,30);status.classList.add('hidden');const meta=document.createElement('div');meta.className='board-meta';const strong=document.createElement('strong');addText(strong,`${best.size} 位调查者`);const stamp=document.createElement('span');addText(stamp,`读取于 ${new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`);meta.append(strong,stamp);board.append(meta);if(ranking.length){const table=document.createElement('table');table.className='leaderboard';table.innerHTML='<thead><tr><th>名次</th><th>调查者</th><th>成绩</th><th>独立答对</th></tr></thead><tbody></tbody>';const tbody=table.querySelector('tbody');ranking.forEach((r,i)=>{const tr=document.createElement('tr'),rank=document.createElement('td'),name=document.createElement('td'),score=document.createElement('td'),correct=document.createElement('td'),a=document.createElement('a');addText(rank,i+1);a.href=r.issueUrl;a.target='_blank';a.rel='noopener';addText(a,r.nickname);name.append(a,document.createElement('br'));const small=document.createElement('small');addText(small,`@${r.login}`);name.append(small);addText(score,`${r.score} / 100`);addText(correct,`${r.correct} / ${r.total}`);tr.append(rank,name,score,correct);tbody.append(tr)});board.append(table)}else{const empty=document.createElement('div');empty.className='empty-board';addText(empty,'还没有公开成绩。完成本章后，你可以成为第一位调查者。');board.append(empty)}const h=document.createElement('h3');h.className='comments-title';addText(h,'玩家留言');board.append(h);if(comments.length){const list=document.createElement('div');list.className='comment-list';comments.forEach(r=>{const item=document.createElement('article');item.className='player-comment';const head=document.createElement('header'),b=document.createElement('b'),stars=document.createElement('span'),time=document.createElement('time'),p=document.createElement('p');addText(b,r.nickname);stars.className='stars';addText(stars,`${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}`);time.dateTime=r.createdAt;addText(time,new Date(r.createdAt).toLocaleDateString('zh-CN'));head.append(b,stars,time);addText(p,r.comment);item.append(head,p);list.append(item)});board.append(list)}else{const empty=document.createElement('div');empty.className='empty-board';addText(empty,'还没有玩家留言。');board.append(empty)}}catch(err){status.textContent='暂时无法读取公共记录。请稍后刷新；你的本地成绩不会丢失。'}}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action;if(act==='start')openReader(0);if(act==='resume')openReader(state.page);if(act==='home')openHome();if(act==='toc'){updateTools();$('#tocDialog').showModal()}if(act==='notebook'){updateTools();$('#notebookDialog').showModal()}if(act==='community'){$('#communityDialog').showModal();loadCommunity()}if(act==='restart'){localStorage.removeItem('mist-memory-ch11-v1');location.reload()}if(act==='inspect')a.closest('.visual').classList.toggle('zoomed')}const jump=e.target.closest('[data-page]');if(jump){$('#tocDialog').close();openReader(+jump.dataset.page)}});
$('#refreshCommunity').onclick=loadCommunity;$('#prevBtn').onclick=()=>{if(state.page>0){state.page--;render()}};$('#nextBtn').onclick=()=>{if(state.page===pages.length-1)openHome();else{state.page++;render()}};$('#sourceBtn').onclick=()=>{$('#sourceText').innerHTML=`<p>${pages[state.page].source}</p>`;$('#sourceDialog').showModal()};$('#soundBtn').onclick=e=>{audioOn=!audioOn;e.currentTarget.setAttribute('aria-pressed',audioOn);e.currentTarget.innerHTML=`<i>${audioOn?'♪':'×'}</i> 声音${audioOn?'开':'关'}`;if(audioOn)tone()};$('#ambientBtn').onclick=()=>setAmbient(!ambientOn);$('#readingMode').onclick=e=>{document.body.classList.toggle('compact');e.currentTarget.textContent=document.body.classList.contains('compact')?'故事模式':'简洁阅读'};openHome();updateTools();
