const $=(s,r=document)=>r.querySelector(s);
const state=JSON.parse(localStorage.getItem('mist-ch11-v2')||'{"page":0,"answers":{},"clues":[],"name":""}');
let audioOn=true,ambientOn=false,audioCtx=null,ambientTimer=null;
const svg={
 town:`<svg viewBox="0 0 640 480" aria-label="钟楼、空气和石墙中的两条传播路线"><defs><linearGradient id="a" y2="1"><stop stop-color="#afc4c9"/><stop offset="1" stop-color="#eadfc8"/></linearGradient></defs><rect width="640" height="480" fill="url(#a)"/><circle cx="520" cy="90" r="62" fill="#eee2bd"/><path d="M0 330V480h640V290c-150 20-280 5-390-30C150 235 80 265 0 330z" fill="#5a625d"/><path d="M70 330V105h120v225" fill="#40544f"/><path d="M52 108l78-86 78 86" fill="#30443f"/><circle cx="130" cy="170" r="32" fill="#c89b4d"/><path d="M130 140v60M100 170h60" stroke="#33433e" stroke-width="6"/><path d="M200 185Q400 155 548 250" fill="none" stroke="#f6f3e8" stroke-width="5" stroke-dasharray="13 11"/><path d="M190 300Q380 305 548 310" fill="none" stroke="#d2a352" stroke-width="8"/><circle cx="556" cy="252" r="17" fill="#33443f"/><path d="M556 270v76" stroke="#33443f" stroke-width="18"/></svg>`,
 ear:`<svg viewBox="0 0 640 480" aria-label="手掌贴着石墙听钟声"><rect width="640" height="480" fill="#b9c5bd"/><path d="M0 0h365v480H0z" fill="#666d67"/><g stroke="#8d948b" stroke-width="5"><path d="M0 100h365M0 205h365M0 315h365M105 0v480M245 0v480"/></g><path d="M420 480V230c0-80 120-80 120 0v250" fill="#2e4540"/><circle cx="480" cy="150" r="70" fill="#c8936d"/><path d="M426 160q50 38 101 0" fill="none" stroke="#31433e" stroke-width="6"/><path d="M408 250q-65-35-110 20" fill="none" stroke="#c8936d" stroke-width="28" stroke-linecap="round"/><g fill="none" stroke="#d3a24e" stroke-width="7"><path d="M270 215q70-55 145-10"/><path d="M245 175q100-80 195-18"/></g></svg>`,
 particles:`<svg viewBox="0 0 640 480" aria-label="固体与空气粒子接力振动"><rect width="640" height="480" fill="#e6e9df"/><text x="160" y="55" text-anchor="middle" fill="#53675f" font-size="22">石墙</text><text x="480" y="55" text-anchor="middle" fill="#53675f" font-size="22">空气</text><path d="M320 25v430" stroke="#c9cec5"/><g fill="#4e7568">${Array.from({length:35},(_,i)=>`<circle cx="${50+(i%7)*38}" cy="${115+Math.floor(i/7)*58}" r="13"/>`).join('')}</g><g fill="#8aa5a1">${Array.from({length:14},(_,i)=>`<circle cx="${370+(i%4)*72}" cy="${100+Math.floor(i/4)*95+(i%2)*18}" r="12"/>`).join('')}</g><g fill="none" stroke="#c28f40" stroke-width="7"><path d="M45 405q110-50 225 0"/><path d="M370 405q100-50 210 0"/></g></svg>`,
 water:`<svg viewBox="0 0 640 480" aria-label="鲸歌穿过海水"><defs><linearGradient id="w" y2="1"><stop stop-color="#9bc9cc"/><stop offset=".18" stop-color="#4c8e9d"/><stop offset="1" stop-color="#174f62"/></linearGradient></defs><rect width="640" height="480" fill="url(#w)"/><path d="M0 70q80-22 160 0t160 0 160 0 160 0" fill="none" stroke="#d7eeee" stroke-width="8"/><path d="M105 260q95-70 205 0-95 90-205 0m205 0 70-48-15 58 15 55z" fill="#203f4b"/><circle cx="160" cy="246" r="5" fill="#d9e9e8"/><g fill="none" stroke="#add8d7" stroke-width="6" opacity=".8"><path d="M350 235q65-45 120 0"/><path d="M370 195q90-60 165 3"/><path d="M390 155q120-73 210 8"/></g><g fill="none" stroke="#d8eeee" stroke-width="3"><circle cx="100" cy="170" r="12"/><circle cx="80" cy="130" r="6"/></g></svg>`,
 vacuum:`<svg viewBox="0 0 640 480" aria-label="玻璃钟罩中的铃铛与逐渐减少的空气"><rect width="640" height="480" fill="#dfe6e2"/><rect x="90" y="400" width="460" height="25" rx="8" fill="#496159"/><path d="M180 390V180c0-100 280-100 280 0v210" fill="#cfe1e133" stroke="#6f9290" stroke-width="8"/><path d="M287 160h66v20h-66zM300 180h40l42 130H258z" fill="#b88943"/><circle cx="320" cy="321" r="17" fill="#815f31"/><g id="dots" fill="#6f9b9a">${Array.from({length:24},(_,i)=>`<circle cx="${210+(i%6)*45}" cy="${190+Math.floor(i/6)*48}" r="4"/>`).join('')}</g><g fill="none" stroke="#bd8f47" stroke-width="6"><path d="M235 250q-25 35 0 70"/><path d="M405 250q25 35 0 70"/></g></svg>`,
 space:`<svg viewBox="0 0 640 480" aria-label="宇航员在真空中看见远处爆发却听不见声音"><rect width="640" height="480" fill="#172b3a"/><g fill="#dce5df">${Array.from({length:45},(_,i)=>`<circle cx="${(i*83)%620+10}" cy="${(i*47)%450+10}" r="${i%5===0?2:1}"/>`).join('')}</g><circle cx="100" cy="110" r="67" fill="#d6a04f"/><circle cx="520" cy="360" r="115" fill="#497b85"/><path d="M430 310q85-55 175 10" fill="none" stroke="#93bbb7" stroke-width="22"/><circle cx="340" cy="220" r="42" fill="#dbe2df"/><rect x="306" y="254" width="70" height="92" rx="30" fill="#ccd8d5"/><path d="M307 280l-65 50M375 280l58-42M323 340l-30 75M360 340l42 70" stroke="#ccd8d5" stroke-width="22" stroke-linecap="round"/><path d="M128 130L300 205" stroke="#e8c477" stroke-width="9" opacity=".7"/></svg>`
};

const pages=[
 {title:'钟楼只敲了一下',skill:'看清异常',kind:'story',visual:'town',caption:'旧城广场 · 雨后的上午',chapter:'第 1 页 · 异常出现',text:'钟楼的铜钟落下一记低沉的声响。你站在石墙后，本该只听见一次，却先从掌心感到一声闷响，片刻后，耳边又传来第二声。',evidence:['现场','同一口钟只敲了一次','异常','你听见了两个抵达时刻','先别解释','先把现象写清楚'],source:'一次敲击可以产生同一个振动源，但声波可能沿不同介质、不同路径抵达观察者。'},
 {title:'哪一条线索最值得追？',skill:'提出假设',kind:'question',visual:'ear',prompt:'要解释“两次钟声”，你最先应该比较什么？',options:[['bells','附近是否还藏着另一口钟'],['paths','声音沿石墙和空气抵达所用的时间'],['loud','钟声到底够不够响']],correct:'paths',feedback:'同一次振动如果走过两条传播速度不同的路径，就可能出现两个抵达时刻。先比较路径，而不是急着发明第二口钟。',clue:['两条路','同一次振动可能沿石墙与空气分别抵达。'],source:'控制其他条件不变，比较两条传播路径，是检验“路径假设”的直接办法。'},
 {title:'让两条路同时出发',skill:'设计比较',kind:'lab',source:'常温空气中的声速约为 343 m/s；石材中的纵波速度通常为数千 m/s，数值随材料而变。'},
 {title:'快的不是声音，是接力方式',skill:'解释机制',kind:'story',visual:'particles',caption:'把石墙和空气“放大”',chapter:'第 4 页 · 微观线索',text:'声音不是从钟里飞出的透明小球。钟的振动推动邻近粒子，粒子再把扰动传给下一层。石墙里的粒子连接更紧密，机械扰动通常传得更快。',evidence:['石墙','粒子连接紧密，扰动传得快','空气','粒子稀疏，传播较慢','关键','声速取决于介质及其状态'],source:'声音是机械波。声速由介质的弹性与密度等性质共同决定，不能只用“粒子距离”单独解释。'},
 {title:'声音究竟是什么？',skill:'建立模型',kind:'question',visual:'particles',prompt:'如果把声音放到“显微镜”下，最接近事实的描述是：',options:[['thing','从声源飞出的一种物质'],['wave','介质中的振动与扰动向外传播'],['light','一种人眼看不见的光']],correct:'wave',feedback:'声音传播的是能量与扰动，并不是把一团空气从钟楼搬到你的耳朵。',clue:['机械波','声音是介质中振动的传播，不是某种“声音物质”在飞行。'],source:'声源振动引起介质的压缩与稀疏，形成机械波；介质粒子只在平衡位置附近振动。'},
 {title:'海里也有一座桥',skill:'迁移解释',kind:'story',visual:'water',caption:'深海 · 鲸的低频歌声',chapter:'第 6 页 · 换一种介质',text:'如果声音只能在空气里前进，鲸的歌声就不可能穿过深海。水也能传递机械振动，而且海水中的声速通常约为 1500 m/s，远高于空气。',evidence:['空气','约 343 m/s','海水','通常约 1500 m/s','结论','声音需要介质，但介质不一定是空气'],source:'海水声速受温度、盐度和压力影响，约 1500 m/s 是常见近似值。'},
 {title:'把空气一点点拿走',skill:'检验预测',kind:'vacuum',source:'经典钟罩实验表明：抽走空气后，铃仍可振动，但外部听到的声音会显著减弱。完全真空是理想化状态。'},
 {title:'什么都没有的地方呢？',skill:'作出预测',kind:'question',visual:'vacuum',prompt:'玻璃罩里的铃仍在振动。当空气接近被抽空，外面的人会怎样？',options:[['same','仍听见同样响的铃声'],['quiet','铃声越来越弱，接近真空时几乎听不到'],['higher','铃声会变得更高']],correct:'quiet',feedback:'声源还在振动，但“接力者”越来越少。没有介质，机械声波就无法把振动传到外面。',clue:['真空边界','声源可以在振动；没有介质时，声音却无法向外传播。'],source:'真空不能传播机械声波。这不等于真空中“什么都不能传播”：电磁波（如光）可以。'},
 {title:'太空中的无声爆发',skill:'区分两种传播',kind:'story',visual:'space',caption:'近地轨道 · 真空',chapter:'第 9 页 · 最后一块证据',text:'电影里，太空爆炸常伴随巨响。现实中，远处的宇航员可以看到光，却听不到爆炸声穿过真空。光不需要物质介质，机械声波需要。',evidence:['能抵达','光、电磁波','不能抵达','穿过真空的机械声波','别混淆','“看见爆发”不等于“听见爆发”'],source:'光是电磁波，可以在真空传播；声音是机械波，传播需要物质介质。'},
 {title:'回到那面石墙',skill:'接起证据链',kind:'question',visual:'town',prompt:'现在，哪条证据链能完整解释“两次钟声”？',options:[['echo','钟声先在空气中传播，再从墙面反射成回声'],['chain','同一次振动沿石墙与空气传播；石墙中更快，所以贴墙听到的先抵达'],['vac','墙内接近真空，所以声音更快']],correct:'chain',feedback:'你把异常、比较实验和传播模型接起来了：不是两口钟，也不是幽灵，而是同一次振动走了两条速度不同的路。',clue:['完整解释','同一次振动沿不同介质传播；石墙路径更快，形成两个抵达时刻。'],source:'解释应同时覆盖“只有一次敲击”“听到两次”和“贴墙的先到”三条观察。'},
 {title:'你的声音地图',skill:'整理证据',kind:'map',source:'本章使用近似值帮助比较。真实声速还会随温度、材料组成和结构而变化。'},
 {title:'调查归档',skill:'查看成绩',kind:'result',source:'你可以重玩来改进成绩；错误不会阻止继续，它们用于显示你的推理如何发生变化。'}
];

function save(){localStorage.setItem('mist-ch11-v2',JSON.stringify(state))}
function tone(f=330,d=.12,v=.025){if(!audioOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(v,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d)}catch(e){}}
function bell(){tone(120,.85,.045);setTimeout(()=>tone(235,.55,.018),55)}
function setAmbient(on){ambientOn=on;$('#ambientBtn').textContent=`氛围声${on?'开':'关'}`;clearInterval(ambientTimer);if(on){tone(180,.8,.008);ambientTimer=setInterval(()=>tone(160+Math.random()*70,.9,.006),3500)}}
function storyHTML(p){return `<div class="story-grid"><figure class="visual"><figcaption>${p.caption}</figcaption>${svg[p.visual]}<button class="inspect" data-action="inspect">查看图像 ↗</button></figure><section class="copy"><p class="chapter">${p.chapter}</p><h1>${p.title}</h1><p>${p.text}</p><div class="clue-card">${p.evidence.map((x,i)=>i%2===0?`<div><small>${x}</small><b>${p.evidence[i+1]}</b></div>`:'').join('')}</div></section></div>`}
function questionHTML(p,i){const previous=state.answers[i];return `<section class="question-page"><header><p>推理节点 · 选择最能解释现有证据的答案</p><h1>${p.title}</h1><p>${p.prompt}</p></header><div class="question-stage"><div class="mini-visual">${svg[p.visual]}</div><div><div class="answers">${p.options.map(o=>`<button class="answer ${previous?(o[0]===p.correct?'correct':(o[0]===previous.choice?'wrong':'')):''}" data-answer="${o[0]}" ${previous?'disabled':''}>${o[1]}</button>`).join('')}</div><div class="feedback ${previous?'':'hidden'}">${previous?`<b>${previous.correct?'证据吻合。':'这条路暂时不通。'}</b><br>${p.feedback}`:''}</div></div></div></section>`}
function labHTML(){return `<section class="lab"><p class="kicker">实验台 · 同时出发</p><h1>哪一条路先抵达？</h1><p>敲一下钟。金色波纹沿石墙前进，白色波纹穿过空气。它们的路程相同，只改变传播介质。</p><div class="race"><div class="tower"></div><div class="air-route"></div><div class="wall-route"></div><i class="pulse air" style="--time:2.4s"></i><i class="pulse solid" style="--time:.65s"></i><div class="listener">♟</div></div><button class="run-test">敲一下并计时</button><div class="measurements"><div>石墙路径<br><b id="solidRead">等待实验</b></div><div>空气路径<br><b id="airRead">等待实验</b></div></div></section>`}
function vacuumHTML(){return `<section class="lab"><p class="kicker">实验台 · 抽走介质</p><h1>铃还在动，声音去哪了？</h1><p>拖动滑杆抽走空气。观察“铃的振动”和“外部听到的声音”是否同时消失。</p><div class="question-stage"><div class="mini-visual">${svg.vacuum}</div><div><label>钟罩内空气：<b id="airValue">100%</b></label><input id="vacSlider" type="range" min="0" max="100" value="100"><div class="feedback"><b>观察记录</b><br><span id="vacText">铃在振动，空气把振动传到罩外。</span></div></div></div></section>`}
function mapHTML(){return `<section class="result-page"><p class="kicker">线索本 · 四站地图</p><h1>一场看不见的接力</h1><p>钟的振动没有“飞”到你身边。抵达你的是介质中一层层传递的扰动。</p><div class="result-grid"><div><b>343</b>m/s<br>常温空气</div><div><b>≈1500</b>m/s<br>海水</div><div><b>0</b>真空中的声传播</div></div><div class="evidence"><b>你的最终模型</b>声源振动 → 介质接力 → 扰动传播 → 耳膜振动 → 听见声音</div></section>`}
function resultHTML(){const qs=pages.map((p,i)=>p.kind==='question'?i:null).filter(i=>i!==null);const correct=qs.filter(i=>state.answers[i]?.correct).length;const attempts=qs.reduce((n,i)=>n+(state.answers[i]?.attempts||0),0);const score=Math.round((correct/qs.length)*70+Math.max(0,30-(attempts-correct)*6));return `<section class="result-page"><p class="kicker">第十一章 · 调查完成</p><h1>${score>=90?'证据链已经闭合':score>=70?'你找到了关键路径':'再回看一次线索本'}</h1><div class="score-ring" style="--score:${score*3.6}deg"><strong>${score}</strong></div><p>你没有直接接过答案，而是从异常出发，改变条件、比较介质，最后解释了墙后的两次钟声。</p><div class="result-grid"><div><b>${correct}/4</b>最终判断</div><div><b>${state.clues.length}</b>条线索</div><div><b>${attempts}</b>次尝试</div></div><div class="name-row"><input id="playerName" maxlength="16" placeholder="写下你的名字（仅保存在本机）" value="${state.name||''}"><button id="saveName">保存成绩</button></div><div class="result-actions"><button class="light" data-action="notebook">回看线索本</button><button class="light" data-action="restart">重新调查</button><a href="https://github.com/taomuzhaotao/chapter11/issues/new?title=%E7%8E%A9%E5%AE%B6%E7%95%99%E8%A8%80&body=%E6%88%91%E5%AE%8C%E6%88%90%E4%BA%86%E3%80%8A%E5%A2%99%E5%90%8E%E7%9A%84%E4%B8%A4%E6%AC%A1%E9%92%9F%E5%A3%B0%E3%80%8B%EF%BC%8C%E6%88%91%E7%9A%84%E5%8F%91%E7%8E%B0%E6%98%AF%EF%BC%9A" target="_blank" rel="noopener">留言与建议 ↗</a></div></section>`}
function render(){state.page=Math.max(0,Math.min(pages.length-1,state.page));const p=pages[state.page];$('#skillLabel').textContent=p.skill;$('#pageNumber').textContent=`${String(state.page+1).padStart(2,'0')} / ${pages.length}`;$('#progressBar').style.width=`${(state.page+1)/pages.length*100}%`;$('#prevBtn').disabled=state.page===0;$('#nextBtn').disabled=p.kind==='question'&&!state.answers[state.page];$('#nextBtn').textContent=state.page===pages.length-1?'回到封面':'下一页';$('#sourceBtn').disabled=false;$('#page').innerHTML=p.kind==='story'?storyHTML(p):p.kind==='question'?questionHTML(p,state.page):p.kind==='lab'?labHTML():p.kind==='vacuum'?vacuumHTML():p.kind==='map'?mapHTML():resultHTML();save();bindPage();updateTools();window.scrollTo({top:0,behavior:'smooth'});if(state.page===0)setTimeout(bell,450)}
function bindPage(){document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));$('.run-test')?.addEventListener('click',()=>{const race=$('.race');race.classList.remove('running');void race.offsetWidth;race.classList.add('running');bell();$('#solidRead').textContent='先到 · 约 0.03 秒';$('#airRead').textContent='后到 · 约 0.29 秒';tone(520,.18,.02)});const v=$('#vacSlider');if(v)v.oninput=()=>{const n=+v.value;$('#airValue').textContent=n+'%';$('#dots').style.opacity=.08+.92*n/100;$('#vacText').textContent=n>60?'铃在振动，空气把振动传到罩外。':n>15?'铃仍在振动，但接力粒子减少，声音变弱。':'接近真空：铃仍在振动，罩外却几乎听不见。';tone(180+n*1.5,.08,.008*n/100)};$('#saveName')?.addEventListener('click',()=>{state.name=$('#playerName').value.trim();save();$('#saveName').textContent='已保存 ✓'})}
function answer(choice){const p=pages[state.page],correct=choice===p.correct,old=state.answers[state.page];state.answers[state.page]={choice,correct,attempts:(old?.attempts||0)+1};if(p.clue&&!state.clues.includes(p.clue[0]))state.clues.push(p.clue[0]);tone(correct?520:170,correct?.18:.28,.025);render()}
function updateTools(){$('#clueCount').textContent=state.clues.length;$('#tocList').innerHTML=pages.map((p,i)=>`<li><button data-page="${i}" class="${i<=state.page?'done':''}"><span>${String(i+1).padStart(2,'0')} · ${p.title}</span></button></li>`).join('');$('#clueList').innerHTML=state.clues.length?state.clues.map(name=>{const p=pages.find(x=>x.clue?.[0]===name);return `<div class="clue"><b>${name}</b><p>${p?.clue?.[1]||''}</p></div>`}).join(''):'<p class="empty">线索还没有出现。继续阅读，在关键判断处收集它们。</p>'}
function openReader(page=0){$('#home').classList.add('hidden');$('#reader').classList.remove('hidden');state.page=page;render()}
function openHome(){$('#reader').classList.add('hidden');$('#home').classList.remove('hidden');$('.resume').classList.toggle('hidden',!localStorage.getItem('mist-ch11-v2'));window.scrollTo(0,0)}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const act=a.dataset.action;if(act==='start')openReader(0);if(act==='resume')openReader(state.page);if(act==='home')openHome();if(act==='toc'){updateTools();$('#tocDialog').showModal()}if(act==='notebook'){updateTools();$('#notebookDialog').showModal()}if(act==='restart'){localStorage.removeItem('mist-ch11-v2');location.reload()}if(act==='inspect')a.closest('.visual').classList.toggle('zoomed')}const jump=e.target.closest('[data-page]');if(jump){$('#tocDialog').close();openReader(+jump.dataset.page)}});
$('#prevBtn').onclick=()=>{if(state.page>0){state.page--;render()}};$('#nextBtn').onclick=()=>{if(state.page===pages.length-1)openHome();else{state.page++;render()}};$('#sourceBtn').onclick=()=>{$('#sourceText').innerHTML=`<p>${pages[state.page].source}</p>`;$('#sourceDialog').showModal()};$('#soundBtn').onclick=e=>{audioOn=!audioOn;e.currentTarget.setAttribute('aria-pressed',audioOn);e.currentTarget.innerHTML=`<i>${audioOn?'♪':'×'}</i> 声音${audioOn?'开':'关'}`;if(audioOn)tone()};$('#ambientBtn').onclick=()=>setAmbient(!ambientOn);$('#readingMode').onclick=e=>{document.body.classList.toggle('compact');e.currentTarget.textContent=document.body.classList.contains('compact')?'故事模式':'简洁阅读'};openHome();updateTools();
